apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-sample
  region: ap-south-1

nodeGroups:
  - name: sample-ng-1
    instanceType: t2.small
    desiredCapacity: 4
    ssh: # use existing EC2 key
      publicKeyName: new-key
  - name: ng-mixed
    minSize: 3
    maxSize: 5
    instancesDistribution:
      maxPrice: 0.2
      instanceTypes: ["t2.small", "t3.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
    ssh: 
      publicKeyName: new-key